# Generated by Django 3.0.2 on 2020-01-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('usermail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='Account Created')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comtext', models.CharField(max_length=200)),
                ('com_date', models.DateTimeField(verbose_name='comment date')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.Topic')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.User')),
            ],
        ),
    ]
