# Generated by Django 3.0.2 on 2020-01-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
    ]
