# Generated by Django 3.0.2 on 2020-01-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20200129_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='writer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='user',
        ),
    ]
